"use client";
import { useMemo, useState } from "react";
import { Plus, RotateCcw, Share2, FileText } from "lucide-react";
const rates={সাধারণ:{low:2600,high:3600},মাঝারি:{low:3200,high:4400},উন্নত:{low:4000,high:5600}} as const;
function n(x:number){return x.toLocaleString("bn-BD",{maximumFractionDigits:0})}
export default function CostCalculator(){
 const [area,setArea]=useState(1200); const [type,setType]=useState<keyof typeof rates>("মাঝারি"); const [city,setCity]=useState("ঢাকা"); const [r,setR]=useState<typeof rates["মাঝারি"]|null>(null);
 const factor=city==="ঢাকা"?1:city==="চট্টগ্রাম"?0.95:city==="সিলেট"?0.98:0.92;
 const calculate=()=>setR({low:rates[type].low*factor,high:rates[type].high*factor});
 const text=useMemo(()=>r?`নির্মাণ খরচের আনুমানিক হিসাব\nআয়তন: ${n(area)} বর্গফুট\nধরন: ${type}\nএলাকা: ${city}\nআনুমানিক খরচ: ৳${n(area*r.low)} – ৳${n(area*r.high)}\n\nএটি পরিকল্পনার জন্য আনুমানিক range; প্রকৃত খরচ নকশা, উপকরণ, শ্রম ও স্থানীয় বাজারদরের ওপর নির্ভর করবে।`:"",[r,area,type,city]);
 function add(){if(!r)return;const p=JSON.parse(localStorage.getItem("nirman-project")||'{"name":"আমার নতুন বাড়ি","items":[]}');p.items=[...(p.items||[]),{title:"নির্মাণ খরচের আনুমানিক বাজেট",quantity:`${n(area)} বর্গফুট · ${type} · ${city}`,cost:Math.round(area*(r.low+r.high)/2),at:new Date().toISOString()}];p.updated=new Date().toISOString();localStorage.setItem("nirman-project",JSON.stringify(p));alert("প্রজেক্টে যোগ হয়েছে।");}
 function share(){if(!r)return; if(navigator.share) navigator.share({title:"নির্মাণ খরচের হিসাব",text}); else navigator.clipboard?.writeText(text).then(()=>alert("ফলাফল কপি হয়েছে।"));}
 return <div className="soft-card p-5 md:p-8 grid lg:grid-cols-[1fr_.85fr] gap-7"><div className="grid sm:grid-cols-2 gap-5"><label className="grid gap-2 sm:col-span-2"><span className="font-bold">বাড়ির আয়তন</span><span className="input-box"><input type="number" min="1" value={area} onChange={e=>setArea(Number(e.target.value))}/><span className="input-unit">বর্গফুট</span></span></label><label className="grid gap-2"><span className="font-bold">নির্মাণের ধরন</span><select value={type} onChange={e=>setType(e.target.value as keyof typeof rates)} className="input-box px-4 py-3 outline-none"><option>সাধারণ</option><option>মাঝারি</option><option>উন্নত</option></select></label><label className="grid gap-2"><span className="font-bold">এলাকা</span><select value={city} onChange={e=>setCity(e.target.value)} className="input-box px-4 py-3 outline-none"><option>ঢাকা</option><option>চট্টগ্রাম</option><option>সিলেট</option><option>অন্যান্য</option></select></label><button onClick={calculate} className="sm:col-span-2 rounded-2xl bg-[var(--green)] text-white py-4 font-black text-lg">আনুমানিক খরচ হিসাব করুন</button></div><div className="rounded-[28px] bg-[var(--surface)] p-6 md:p-7 min-h-[300px]">{!r?<div className="h-full grid place-items-center text-center text-[var(--muted)]">আয়তন ও নির্মাণের ধরন নির্বাচন করে হিসাব করুন।</div>:<><div className="text-[var(--green)] font-black">আনুমানিক মোট খরচ</div><div className="text-3xl md:text-4xl font-black mt-2">৳{n(area*r.low)} – ৳{n(area*r.high)}</div><p className="text-sm text-[var(--muted)] leading-6 mt-3">এটি বাজারদরের সাধারণ range ধরে পরিকল্পনামূলক estimate। সঠিক বাজেটের জন্য BOQ, নকশা, শ্রম ও বর্তমান স্থানীয় দর যাচাই করুন।</p><div className="flex flex-wrap gap-2 mt-5"><button onClick={add} className="rounded-xl bg-[var(--card)] border border-[var(--line)] px-4 py-2 font-bold flex gap-2 items-center"><Plus size={16}/> প্রজেক্টে যোগ</button><button onClick={share} className="rounded-xl bg-[var(--card)] border border-[var(--line)] px-4 py-2 font-bold flex gap-2 items-center"><Share2 size={16}/> শেয়ার</button><button onClick={()=>window.location.href="/report"} className="rounded-xl bg-[var(--card)] border border-[var(--line)] px-4 py-2 font-bold flex gap-2 items-center"><FileText size={16}/> রিপোর্ট</button><button onClick={()=>setR(null)} className="rounded-xl bg-[var(--card)] border border-[var(--line)] px-4 py-2 font-bold flex gap-2 items-center"><RotateCcw size={16}/> নতুন হিসাব</button></div></>}</div></div>
}
