
import Link from "next/link";import {notFound} from "next/navigation";import {articles} from "../../../lib/site";
const body:any={
"ghorer-deyale-koto-rong-lagbe":["চারটি দেয়ালের মোট ক্ষেত্রফল বের করে দরজা ও জানালার জায়গা বাদ দিতে হয়। এরপর কতটি কোট দেওয়া হবে এবং প্রতি লিটারে কত বর্গফুট রং করা যায় তা ধরে প্রয়োজনীয় রং বের করা যায়।","রঙের ব্র্যান্ড, দেয়ালের শোষণক্ষমতা, প্রাইমার ও কাজের ধরন অনুযায়ী প্রকৃত coverage পরিবর্তিত হতে পারে। তাই রঙের পাত্রে দেওয়া coverage-কে অগ্রাধিকার দিন।"],
"1000-borgofut-deyale-koto-it":["শুধু ১০০০ বর্গফুট area জানলে ইটের সংখ্যা নির্ভুলভাবে বলা যায় না। দেয়ালের পুরুত্ব এবং ইটের প্রকৃত মাপও দরকার।","মর্টারের joint, workmanship এবং ইটের মাপের পার্থক্যের জন্য বাস্তব consumption বদলাতে পারে।"],
"chade-koto-cement-bali":["ছাদের concrete volume সাধারণভাবে দৈর্ঘ্য × প্রস্থ × পুরুত্ব দিয়ে বের করা হয়। এরপর শুকনো হিসাবের গুণক ও নির্দিষ্ট মিশ্রণের অনুপাত ব্যবহার করে সিমেন্ট, বালি ও খোয়ার আনুমানিক পরিমাণ পাওয়া যায়।","Structural slab-এর mix ও strength অবশ্যই প্রকৌশলীর নকশা এবং অনুমোদিত mix design অনুযায়ী হতে হবে।"],
"tiles-koto-lagbe":["মেঝের ক্ষেত্রফলকে একটি টাইলসের ক্ষেত্রফল দিয়ে ভাগ করলে প্রাথমিক টাইলস সংখ্যা পাওয়া যায়। কাটাকাটি ও ভাঙার জন্য অতিরিক্ত অপচয় যোগ করা উচিত।","Diagonal pattern বা বেশি কাটাকাটি থাকলে সাধারণের চেয়ে বেশি অতিরিক্ত টাইলস প্রয়োজন হতে পারে।"],
"ek-ghorer-jonno-koto-litre-rong":["দেয়ালের ক্ষেত্রফল থেকে দরজা-জানালার জায়গা বাদ দিয়ে কোট সংখ্যা দিয়ে গুণ করে coverage দিয়ে ভাগ করুন।","প্রাইমার, putty, surface condition এবং application method অনুযায়ী প্রকৃত রংয়ের প্রয়োজন বদলাতে পারে।"],
"concrete-poriman-kivabe-hisab":["Concrete volume বের করার সহজ সূত্র হলো দৈর্ঘ্য × প্রস্থ × পুরুত্ব। সব মাপ একই এককে রাখুন।","Material breakdown-এর জন্য dry-volume factor ও mix ratio ব্যবহার করা যায়, কিন্তু structural কাজের জন্য nominal ratio নিজে থেকে নির্ধারণ করা উচিত নয়।"]};
export function generateStaticParams(){return articles.map(a=>({slug:a.slug}))}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=articles.find(x=>x.slug===slug);if(!a)notFound();const t=body[slug];return <article className="container max-w-3xl py-12"><div className="text-[#146b48] font-bold">নির্মাণ গাইড</div><h1 className="text-4xl md:text-5xl font-black leading-tight mt-2">{a.title}</h1><p className="text-lg text-[#756e66] leading-8 mt-4">{a.desc}</p><div className="text-lg leading-9 mt-8"><p>{t[0]}</p><p className="mt-5">{t[1]}</p><h2 className="text-2xl font-black mt-9">মনে রাখবেন</h2><ul className="list-disc pl-6 mt-3"><li>সব মাপ একই এককে নিন।</li><li>উপকরণের প্রকৃত specification যাচাই করুন।</li><li>অপচয়ের হার কাজের ধরন অনুযায়ী পরিবর্তন করুন।</li><li>Structural কাজের ক্ষেত্রে প্রকৌশলীর অনুমোদিত নকশা অনুসরণ করুন।</li></ul></div><Link href={"/"+a.calc} className="inline-block mt-8 bg-[#146b48] text-white rounded-2xl px-6 py-3 font-black">এই হিসাবের ক্যালকুলেটর খুলুন</Link></article>}
